# Generated by Django 2.2.1 on 2019-05-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodStart', models.CharField(max_length=100)),
                ('periodEnd', models.CharField(max_length=100)),
                ('equation', models.CharField(max_length=500)),
            ],
        ),
    ]
